language: node_js
node_js:
  - "node"
cache:
  yarn: true
script: yarn build
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: public
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: master
  on:
    tags: true
