language: node_js
node_js:
  - "10"
git:
  depth: 5
cache:
  yarn: true
  directories:
  - .cache
script: yarn build
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: public
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: master
  on:
    tags: true
