name: Build and publish site

on: [push]

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node 10
        uses: actions/setup-node@v3
        with:
          node-version: '10'
          cache: 'yarn'
      - name: Install dependencies with yarn
        run: yarn
      - name: Build site
        run: yarn build
      - name: Upload site content
        uses: actions/upload-artifact@v3
        with:
          name: public
          path: public/
          retention-days: 1
  publish:
    name: Publish to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - name: Download site content
        uses: actions/download-artifact@v3
        with:
          name: public
          path: .
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          path: .
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
